[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[[services]]
name = "web"

[services.web]
source = "."
build.buildCommand = "npm ci && npm run build"
build.watchPatterns = ["src/**"]