[phases.setup]
providers = ["nodejs"]

[phases.install]
cmds = ["echo 'Skipping root install'"]

[phases.build]
cmds = ["cd src && npm ci && npm run build"]

[phases.start]
cmd = "cd src && npm start"
